name: Build and test Ruby Get Started sample

on:
  push:
    branches:
      - main
      - regen/clients-**
    paths:
      - 'get-started/azure-auth/ruby/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'get-started/azure-auth/ruby/**'
      - '.github/workflows/**'

jobs:
  build-azure:

    defaults:
      run:
        working-directory: get-started/azure-auth/ruby/

    runs-on: ubuntu-latest
    needs: []

    steps:
    - uses: actions/checkout@v5

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake
